image: openjdk:12-alpine

stages:
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  script:
    - ./gradlew check

pages:
  stage: deploy
  script:
    - ./gradlew javadoc
    - ls
    - mv ./build/docs/javadoc public
    - ls public
  artifacts:
    paths:
      - public
  only:
    - master